#IFNDEF LCD_RS
#DEFINE LCD_RS PIN_E0
#ENDIF
#IFNDEF LCD_RW 
#DEFINE LCD_RW PIN_E1
#ENDIF
#IFNDEF LCD_E
#DEFINE LCD_E PIN_E2
#ENDIF
#IFNDEF OUTPUT_LCD
#define OUTPUT_LCD OUTPUT_D
#ENDIF
#DEFINE FUNCTION_SET 0X38 //GIAO TIEP 8 BIT, 2 HANG
#DEFINE DISPLAY_CONTROL 0X0F
#DEFINE CLEAR_DISPLAY 0X01
#DEFINE ENTRY_MODE 0X06
#DEFINE SHIFT_LEFT_LCD 0X18
#DEFINE SHIFT_RIGHT_LCD 0X1C
#DEFINE ADDR_LINE1 0X80
#DEFINE ADDR_LINE2 0XC0
void LCD_COMMAND(UNSIGNED CHAR MDK) //RS = 0
{ 
   OUTPUT_LOW(LCD_RS); OUTPUT_LCD(MDK);
   OUTPUT_HIGH(LCD_E); DELAY_MS(20);
   OUTPUT_LOW(LCD_E); DELAY_MS(20);
}
void LCD_DATA(UNSIGNED CHAR MHT) //RS = 1
{ 
 OUTPUT_HIGH(LCD_RS); OUTPUT_LCD(MHT);
 OUTPUT_HIGH(LCD_E); DELAY_MS(20); 
 OUTPUT_LOW(LCD_E); DELAY_MS(20);
}
VOID LCD_SETUP()
{ 
 OUTPUT_LOW(LCD_E); 
 OUTPUT_LOW(LCD_RS); 
 OUTPUT_LOW(LCD_RW);
 LCD_COMMAND(FUNCTION_SET); DELAY_MS(1);
 LCD_COMMAND(DISPLAY_CONTROL);
 LCD_COMMAND(CLEAR_DISPLAY); DELAY_MS(2);
 LCD_COMMAND(ENTRY_MODE);
}//CaoTanPhi-MSSV:20146513
